// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY0u24Yo7wBsZWra26AZFF1Xihkxstqjw',
    appId: '1:958786103937:web:b1195363fb0dbee8d03b80',
    messagingSenderId: '958786103937',
    projectId: 'learn-98d05',
    authDomain: 'learn-98d05.firebaseapp.com',
    storageBucket: 'learn-98d05.appspot.com',
    measurementId: 'G-RDPLHK3G0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7Q7BNLnXFXOFjNEBHzuyDTcxA_3CyjM',
    appId: '1:958786103937:android:3fe694efd1f2dddbd03b80',
    messagingSenderId: '958786103937',
    projectId: 'learn-98d05',
    storageBucket: 'learn-98d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhGfJtc-vNt8zkqR6Qe1nCpa4TwRKG27A',
    appId: '1:958786103937:ios:81f47f3fb53d149ed03b80',
    messagingSenderId: '958786103937',
    projectId: 'learn-98d05',
    storageBucket: 'learn-98d05.appspot.com',
    iosClientId:
        '958786103937-3s6ev3kknedarmup13bcffseqenfsrkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.learn',
  );
}
